### ISSUE TITLE
Issue for the assignment on python course

### ISSUE THREAD

**Issue by sarit-moses** [Lihierez/Lihierez.github.io#1]
Hi, I love your website! To improve it you might want to link your email/github/linkedin in the website, so whoever sees your portfolio can reach out to you.

**Comment by Lihierez** [comment]
Hi Sarit,
Thank you for you suggestion! 
I added a contact me section with links to my linkedin, email and GitHub.

**Comment by sarit-moses** [comment]
@liron99
